# Generated by Django 3.2.8 on 2021-10-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasankabir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='flowpattern',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
